### ISSUE TITLE
Libraries and Techniques used for Face Cropping

### ISSUE THREAD

**Issue by souvikg544** [ms-dot-k/Lip-to-Speech-Synthesis-in-the-Wild#10]
Hello ! Could you please elaborate on the libraries used for Face cropping and is their any alignment done or not. The data preprocessing code would be very helpful.

**Comment by ms-dot-k** [comment]
We didn't apply any special preprocessing as the LRS2 and LRS3 already have the same size of face.
Therefore, we only extracted the center coordinate of the lip landmark from the video and cropped the video with 80 x 80 size (hence, lip-centered).
This preprocessing is done on the fly at the data loader 
(https://github.com/ms-dot-k/Lip-to-Speech-Synthesis-in-the-Wild/blob/c9911a93d0ba5f8f637b85fd3778b10fec1e3577/src/data/vid_aud_lrs2.py#L111-L115).

Hence, if you want to apply it to another dataset with the pre-trained model, you need to align your video by setting one of the frames in LRS2 as a reference frame so that your video can have the same size of face as that of LRS2.
And then you can crop the video at 80 x 80 size centered by the lip landmark coordinates.
