### ISSUE TITLE
Loss

### ISSUE THREAD

**Issue by blackbird-fish** [ms-dot-k/Lip-to-Speech-Synthesis-in-the-Wild#7]
![image](https://github.com/ms-dot-k/Lip-to-Speech-Synthesis-in-the-Wild/assets/68136663/4912199d-5dac-4be4-a590-4d42846336a2)

hello i tried to train on LRS2 dataset but it dose not converge, how  many steps does it take

**Comment by ms-dot-k** [comment]
Can you refer to #2 ?

**Comment by blackbird-fish** [comment]
I get it, can you provide a reference for handling the position of lips? I noticed that the GPU utilization seemed to be a little low during training, would it be better to pre-process the video into lip frames? Using the 2080ti seems to take a long time to converge..

**Comment by ms-dot-k** [comment]
Yeah, that's true. The source code is not optimized in speed and takes several weeks to converge.
Maybe you can try to crop the lip region first by 1) referring the dataset `src/data/vid_aud_lrs2.py' or  2) following https://github.com/mpc001/auto_avsr/tree/main/preparation. The second option produces slightly different lip-centered images from ours as different landmark detectors are utilized, but it would be simpler without coding.

After preprocessing the video, you should modify the `src/data/vid_aud_lrs2.py' so that it starts from resizing.

**Comment by blackbird-fish** [comment]
thanks so much
